INSERT INTO EXCHANGE_VALUE(ID, CONVERSION_FROM, CONVERSION_TO, CONVERSION_MULTIPLE) VALUES(1000, 'USD', 'INR', 83);
INSERT INTO EXCHANGE_VALUE(ID, CONVERSION_FROM, CONVERSION_TO, CONVERSION_MULTIPLE) VALUES(1001, 'EUR', 'INR', 89);
INSERT INTO EXCHANGE_VALUE(ID, CONVERSION_FROM, CONVERSION_TO, CONVERSION_MULTIPLE) VALUES(1002, 'AUD', 'INR', 54);
INSERT INTO EXCHANGE_VALUE(ID, CONVERSION_FROM, CONVERSION_TO, CONVERSION_MULTIPLE) VALUES(1003, 'SD', 'INR', 61);
